export enum OrderStatus {
  PENDING = 'PENDING',
  ROUTED = 'ROUTED',
  ACKNOWLEDGED = 'ACK',
  PARTIALLY_FILLED = 'PARTIAL',
  FILLED = 'FILLED',
  CANCELLED = 'CANCELLED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}
