from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum, auto
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    import polars as pl


class EventType(Enum):
    MARKET_DATA = auto()
    FEATURE = auto()
    SIGNAL = auto()
    ENSEMBLE_SIGNAL = auto()
    ORDER = auto()
    FILL = auto()
    RISK = auto()
    SYSTEM = auto()
    FEEDBACK_UPDATE = auto()
    RETRY_ORDER = auto()
    DRIFT = auto()
    MODEL_RETRAIN = auto()
    ERROR = auto()
    HEARTBEAT = auto()


@dataclass(frozen=True, kw_only=True)
class Event:
    type: EventType
    timestamp: datetime = field(default_factory=datetime.utcnow)
    trace_id: str = field(default_factory=lambda: "pending")  # Should be generated by TraceManager


@dataclass(frozen=True, kw_only=True)
class MarketDataEvent(Event):
    symbol: str
    data: pl.DataFrame | dict[str, Any]  # Can be OHLCV DataFrame or Tick dict
    metadata: dict[str, Any] | None = None
    type: EventType = EventType.MARKET_DATA

    @property
    def bid(self) -> float:
        if isinstance(self.data, dict):
            return float(self.data.get("bid", 0.0))
        return 0.0

    @property
    def ask(self) -> float:
        if isinstance(self.data, dict):
            return float(self.data.get("ask", 0.0))
        return 0.0


@dataclass(frozen=True, kw_only=True)
class FeatureEvent(Event):
    symbol: str
    features: dict[str, pl.Series]  # feature name -> series
    metadata: dict[str, Any] | None = None
    type: EventType = EventType.FEATURE


@dataclass(frozen=True, kw_only=True)
class SignalEvent(Event):
    symbol: str
    signal_type: str  # e.g., 'BUY', 'SELL', 'HOLD'
    strength: float  # Signal strength in [0, 1]
    metadata: dict[str, Any] = field(default_factory=dict)
    type: EventType = EventType.SIGNAL

    @property
    def signal(self) -> float:
        # Compatibility with the [GLOBAL_EVENT_DRIVEN_MIGRATION] contract
        if self.signal_type == "BUY":
            return self.strength
        if self.signal_type == "SELL":
            return -self.strength
        return 0.0

    @property
    def confidence(self) -> float:
        return self.metadata.get("confidence", 0.5)


@dataclass(frozen=True, kw_only=True)
class EnsembleSignalEvent(Event):
    symbol: str
    signal_type: str  # e.g., 'ENSEMBLE'
    strength: float  # Signal strength in [0, 1]
    metadata: dict[str, Any] = field(default_factory=dict)
    type: EventType = EventType.ENSEMBLE_SIGNAL


@dataclass(frozen=True, kw_only=True)
class OrderEvent(Event):
    order_id: str
    symbol: str
    side: str  # 'BUY' or 'SELL'
    order_type: str  # e.g., 'MARKET', 'LIMIT', 'TWAP', 'VWAP'
    quantity: float
    price: float | None = None  # For limit orders
    metadata: dict[str, Any] | None = None
    type: EventType = EventType.ORDER

    @property
    def action(self) -> str:
        return self.side


@dataclass(frozen=True, kw_only=True)
class FillEvent(Event):
    order_id: str
    symbol: str
    side: str  # 'BUY' or 'SELL'
    quantity: float
    price: float
    commission: float = 0.0
    metadata: dict[str, Any] | None = None
    type: EventType = EventType.FILL


@dataclass(frozen=True, kw_only=True)
class RiskEvent(Event):
    symbol: str
    metrics: dict[str, float]  # e.g., {'var': 0.05, 'drawdown': 0.02}
    metadata: dict[str, Any] | None = None
    type: EventType = EventType.RISK


@dataclass(frozen=True, kw_only=True)
class SystemEvent(Event):
    action: str  # e.g., 'START', 'STOP', 'KILL_SWITCH'
    reason: str = ""
    metadata: dict[str, Any] | None = None
    type: EventType = EventType.SYSTEM


@dataclass(frozen=True, kw_only=True)
class RetryOrderEvent(Event):
    order: OrderEvent
    attempt: int
    metadata: dict[str, Any] = field(default_factory=dict)
    type: EventType = EventType.RETRY_ORDER


@dataclass(frozen=True, kw_only=True)
class DriftEvent(Event):
    symbol: str
    drift_score: float
    features: list[str] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)
    type: EventType = EventType.DRIFT


@dataclass(frozen=True, kw_only=True)
class ModelRetrainEvent(Event):
    symbol: str
    model_id: str
    reason: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)
    type: EventType = EventType.MODEL_RETRAIN


@dataclass(frozen=True, kw_only=True)
class ErrorEvent(Event):
    source: str
    message: str
    exception_type: str | None = None
    stack_trace: str | None = None
    severity: str = "ERROR" # INFO, WARNING, ERROR, CRITICAL
    metadata: dict[str, Any] = field(default_factory=dict)
    type: EventType = EventType.ERROR